import { CALLBACK_PHASE, CALLBACK_ROUTE } from '../../router/callbackContracts.js';
import {
  APPLICATION_BRAND_ACTIONS,
  APPLICATION_CREATOR_ACTIONS,
  APPLICATION_DEALS_ACTIONS,
} from './actions.js';

export const APPLICATION_CREATOR_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.APPLICATION_CREATOR,
  phase: CALLBACK_PHASE.POST_USER,
  actions: APPLICATION_CREATOR_ACTIONS,
});

export const APPLICATION_BRAND_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.APPLICATION_BRAND,
  phase: CALLBACK_PHASE.POST_USER,
  actions: APPLICATION_BRAND_ACTIONS,
});

export const APPLICATION_DEALS_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.APPLICATION_DEALS,
  phase: CALLBACK_PHASE.POST_USER,
  actions: APPLICATION_DEALS_ACTIONS,
});

export const APPLICATION_CALLBACK_ROUTE_DEFINITIONS = Object.freeze([
  APPLICATION_CREATOR_ROUTE_DEFINITION,
  APPLICATION_BRAND_ROUTE_DEFINITION,
  APPLICATION_DEALS_ROUTE_DEFINITION,
]);
