export const MODERATION_ACTION = Object.freeze({
  MOD_HOME: 'a:mod_home',
  MOD_REPORTS: 'a:mod_reports',
  MOD_REPORT: 'a:mod_report',
  MOD_REPORT_FREEZE: 'a:mod_r_freeze',
  MOD_REPORT_CLOSE: 'a:mod_r_close',
  MOD_REPORT_RESOLVE: 'a:mod_r_resolve',
  MOD_VERIFICATIONS: 'a:mod_verifs',
  MOD_VERIFICATION_VIEW: 'a:mod_verif_view',
  MOD_VERIFICATION_APPROVE: 'a:mod_verif_approve',
  MOD_VERIFICATION_REJECT: 'a:mod_verif_reject',
});

export const MODERATION_REPORT_ACTIONS = Object.freeze([
  MODERATION_ACTION.MOD_HOME,
  MODERATION_ACTION.MOD_REPORTS,
  MODERATION_ACTION.MOD_REPORT,
  MODERATION_ACTION.MOD_REPORT_FREEZE,
  MODERATION_ACTION.MOD_REPORT_CLOSE,
  MODERATION_ACTION.MOD_REPORT_RESOLVE,
]);

export const MODERATION_VERIFICATION_ACTIONS = Object.freeze([
  MODERATION_ACTION.MOD_VERIFICATIONS,
  MODERATION_ACTION.MOD_VERIFICATION_VIEW,
  MODERATION_ACTION.MOD_VERIFICATION_APPROVE,
  MODERATION_ACTION.MOD_VERIFICATION_REJECT,
]);

export const MODERATION_CALLBACK_ACTIONS = Object.freeze([
  ...MODERATION_REPORT_ACTIONS,
  ...MODERATION_VERIFICATION_ACTIONS,
]);
