import { CALLBACK_PHASE, CALLBACK_ROUTE } from '../../router/callbackContracts.js';
import {
  MODERATION_REPORT_ACTIONS,
  MODERATION_VERIFICATION_ACTIONS,
} from './actions.js';

export const MODERATION_REPORTS_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.MODERATION_REPORTS,
  phase: CALLBACK_PHASE.POST_USER,
  actions: MODERATION_REPORT_ACTIONS,
});

export const MODERATION_VERIFICATION_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.MODERATION_VERIFICATION,
  phase: CALLBACK_PHASE.POST_USER,
  actions: MODERATION_VERIFICATION_ACTIONS,
});

export const MODERATION_CALLBACK_ROUTE_DEFINITIONS = Object.freeze([
  MODERATION_REPORTS_ROUTE_DEFINITION,
  MODERATION_VERIFICATION_ROUTE_DEFINITION,
]);
