export const CALLBACK_PHASE = Object.freeze({
  PRE_USER: 'pre_user',
  POST_USER: 'post_user',
});

export const CALLBACK_ROUTE = Object.freeze({
  ADMIN_WEB_AUTH: 'admin_web_auth',
  ADMIN_WEB_AUTH_CONTROL: 'admin_web_auth_control',
  PAYMENT_PURCHASE: 'payment_purchase',
  PAYMENT_ADMIN: 'payment_admin',
  GIVEAWAY_ACCESS: 'giveaway_access',
  GIVEAWAY_PARTICIPANT: 'giveaway_participant',
  GIVEAWAY_LIFECYCLE: 'giveaway_lifecycle',
  BROADCAST_COMPOSER: 'broadcast_composer',
  BROADCAST_AUDIENCE: 'broadcast_audience',
  BROADCAST_DISPATCH: 'broadcast_dispatch',
  BROADCAST_OPERATIONS: 'broadcast_operations',
  NAVIGATION_SHARED: 'navigation_shared',
  TELEGRAM_UX_SHARED: 'telegram_ux_shared',
  APPLICATION_CREATOR: 'application_creator',
  APPLICATION_BRAND: 'application_brand',
  APPLICATION_DEALS: 'application_deals',
  LEAD_ACQUISITION: 'lead_acquisition',
  LEAD_WORKFLOW: 'lead_workflow',
  LEAD_AUDIT: 'lead_audit',
  BARTER_DISCOVERY: 'barter_discovery',
  BARTER_OFFICIAL: 'barter_official',
  BARTER_CONVERSATIONS: 'barter_conversations',
  BARTER_OFFERS: 'barter_offers',
  WORKSPACE_CONTROL: 'workspace_control',
  WORKSPACE_FOLDERS: 'workspace_folders',
  WORKSPACE_PROFILE: 'workspace_profile',
  WORKSPACE_SOCIAL: 'workspace_social',
  DIRECTORY_SEARCH: 'directory_search',
  DIRECTORY_PUBLIC_WORKSPACE: 'directory_public_workspace',
  BRAND_DIRECTORY: 'brand_directory',
  BRAND_PROFILE: 'brand_profile',
  BRAND_MANAGER_MODE: 'brand_manager_mode',
  BRAND_TEAM_MEMBERSHIP: 'brand_team_membership',
  CURATOR_OPERATIONS: 'curator_operations',
  CURATOR_MANAGEMENT: 'curator_management',
  MODERATION_REPORTS: 'moderation_reports',
  MODERATION_VERIFICATION: 'moderation_verification',
  ADMIN_USERS: 'admin_users',
  ADMIN_GIFTS: 'admin_gifts',
  ADMIN_SUPPORT: 'admin_support',
  ADMIN_MODERATOR_GOVERNANCE: 'admin_moderator_governance',
  LEGACY: 'legacy',
});
