import { CALLBACK_PHASE, CALLBACK_ROUTE } from '../../router/callbackContracts.js';
import {
  DIRECTORY_PUBLIC_WORKSPACE_ACTIONS,
  DIRECTORY_SEARCH_ACTIONS,
} from './actions.js';

export const DIRECTORY_SEARCH_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.DIRECTORY_SEARCH,
  phase: CALLBACK_PHASE.POST_USER,
  actions: DIRECTORY_SEARCH_ACTIONS,
});

export const DIRECTORY_PUBLIC_WORKSPACE_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.DIRECTORY_PUBLIC_WORKSPACE,
  phase: CALLBACK_PHASE.POST_USER,
  actions: DIRECTORY_PUBLIC_WORKSPACE_ACTIONS,
});

export const DIRECTORY_CALLBACK_ROUTE_DEFINITIONS = Object.freeze([
  DIRECTORY_SEARCH_ROUTE_DEFINITION,
  DIRECTORY_PUBLIC_WORKSPACE_ROUTE_DEFINITION,
]);
