import { CALLBACK_PHASE, CALLBACK_ROUTE } from '../../router/callbackContracts.js';
import {
  GIVEAWAY_ACCESS_ACTIONS,
  GIVEAWAY_LIFECYCLE_ACTIONS,
  GIVEAWAY_PARTICIPANT_ACTIONS,
} from './actions.js';

export const GIVEAWAY_ACCESS_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.GIVEAWAY_ACCESS,
  phase: CALLBACK_PHASE.POST_USER,
  actions: GIVEAWAY_ACCESS_ACTIONS,
});

export const GIVEAWAY_PARTICIPANT_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.GIVEAWAY_PARTICIPANT,
  phase: CALLBACK_PHASE.POST_USER,
  actions: GIVEAWAY_PARTICIPANT_ACTIONS,
});

export const GIVEAWAY_LIFECYCLE_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.GIVEAWAY_LIFECYCLE,
  phase: CALLBACK_PHASE.POST_USER,
  actions: GIVEAWAY_LIFECYCLE_ACTIONS,
});

export const GIVEAWAY_CALLBACK_ROUTE_DEFINITIONS = Object.freeze([
  GIVEAWAY_ACCESS_ROUTE_DEFINITION,
  GIVEAWAY_PARTICIPANT_ROUTE_DEFINITION,
  GIVEAWAY_LIFECYCLE_ROUTE_DEFINITION,
]);
