export const USER_SERVICE_ACTION = Object.freeze({
  SUPPORT: 'a:support',
  SUPPORT_PUSH: 'a:support_push',
  SUPPORT_WRITE: 'a:support_write',
  VERIFY_HOME: 'a:verify_home',
  VERIFY_INFO: 'a:verify_info',
  VERIFY_KIND: 'a:verify_kind',
  SHARE: 'a:share',
  SHARE_PERFORMANCE: 'a:share_perf',
  SHARE_POINTS: 'a:share_points',
  SHARE_LINK: 'a:share_link',
  SHARE_CARD: 'a:share_card',
  SHARE_HISTORY: 'a:share_history',
  SHARE_REWARDS: 'a:share_rewards',
  SHARE_REDEEM: 'a:share_redeem',
  SHARE_REDEEM_DO: 'a:share_redeem_do',
  ACCOUNT_DELETE_CONFIRM: 'a:acc_del_q',
  ACCOUNT_DELETE: 'a:acc_del_do',
  ACCOUNT_RESTORE: 'a:acc_restore',
});

export const USER_SUPPORT_ACTIONS = Object.freeze([
  USER_SERVICE_ACTION.SUPPORT,
  USER_SERVICE_ACTION.SUPPORT_PUSH,
  USER_SERVICE_ACTION.SUPPORT_WRITE,
]);

export const USER_VERIFICATION_ACTIONS = Object.freeze([
  USER_SERVICE_ACTION.VERIFY_HOME,
  USER_SERVICE_ACTION.VERIFY_INFO,
  USER_SERVICE_ACTION.VERIFY_KIND,
]);

export const USER_SHARING_ACTIONS = Object.freeze([
  USER_SERVICE_ACTION.SHARE,
  USER_SERVICE_ACTION.SHARE_PERFORMANCE,
  USER_SERVICE_ACTION.SHARE_POINTS,
  USER_SERVICE_ACTION.SHARE_LINK,
  USER_SERVICE_ACTION.SHARE_CARD,
  USER_SERVICE_ACTION.SHARE_HISTORY,
  USER_SERVICE_ACTION.SHARE_REWARDS,
  USER_SERVICE_ACTION.SHARE_REDEEM,
  USER_SERVICE_ACTION.SHARE_REDEEM_DO,
]);

export const USER_ACCOUNT_ACTIONS = Object.freeze([
  USER_SERVICE_ACTION.ACCOUNT_DELETE_CONFIRM,
  USER_SERVICE_ACTION.ACCOUNT_DELETE,
  USER_SERVICE_ACTION.ACCOUNT_RESTORE,
]);

export const USER_SERVICE_CALLBACK_ACTIONS = Object.freeze([
  ...USER_SUPPORT_ACTIONS,
  ...USER_VERIFICATION_ACTIONS,
  ...USER_SHARING_ACTIONS,
  ...USER_ACCOUNT_ACTIONS,
]);
