import { CALLBACK_PHASE, CALLBACK_ROUTE } from '../../router/callbackContracts.js';
import {
  USER_ACCOUNT_ACTIONS,
  USER_SHARING_ACTIONS,
  USER_SUPPORT_ACTIONS,
  USER_VERIFICATION_ACTIONS,
} from './actions.js';

export const USER_SUPPORT_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.USER_SUPPORT,
  phase: CALLBACK_PHASE.POST_USER,
  actions: USER_SUPPORT_ACTIONS,
});

export const USER_VERIFICATION_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.USER_VERIFICATION,
  phase: CALLBACK_PHASE.POST_USER,
  actions: USER_VERIFICATION_ACTIONS,
});

export const USER_SHARING_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.USER_SHARING,
  phase: CALLBACK_PHASE.POST_USER,
  actions: USER_SHARING_ACTIONS,
});

export const USER_ACCOUNT_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.USER_ACCOUNT,
  phase: CALLBACK_PHASE.POST_USER,
  actions: USER_ACCOUNT_ACTIONS,
});

export const USER_SERVICE_CALLBACK_ROUTE_DEFINITIONS = Object.freeze([
  USER_SUPPORT_ROUTE_DEFINITION,
  USER_VERIFICATION_ROUTE_DEFINITION,
  USER_SHARING_ROUTE_DEFINITION,
  USER_ACCOUNT_ROUTE_DEFINITION,
]);
