import { CALLBACK_PHASE, CALLBACK_ROUTE } from '../../router/callbackContracts.js';
import {
  ADMIN_USER_ACTIONS,
  ADMIN_GIFT_ACTIONS,
  ADMIN_SUPPORT_ACTIONS,
  ADMIN_MODERATOR_GOVERNANCE_ACTIONS,
} from './actions.js';

export const ADMIN_USERS_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.ADMIN_USERS,
  phase: CALLBACK_PHASE.POST_USER,
  actions: ADMIN_USER_ACTIONS,
});

export const ADMIN_GIFTS_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.ADMIN_GIFTS,
  phase: CALLBACK_PHASE.POST_USER,
  actions: ADMIN_GIFT_ACTIONS,
});

export const ADMIN_SUPPORT_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.ADMIN_SUPPORT,
  phase: CALLBACK_PHASE.POST_USER,
  actions: ADMIN_SUPPORT_ACTIONS,
});

export const ADMIN_MODERATOR_GOVERNANCE_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.ADMIN_MODERATOR_GOVERNANCE,
  phase: CALLBACK_PHASE.POST_USER,
  actions: ADMIN_MODERATOR_GOVERNANCE_ACTIONS,
});

export const ADMIN_OPERATION_CALLBACK_ROUTE_DEFINITIONS = Object.freeze([
  ADMIN_USERS_ROUTE_DEFINITION,
  ADMIN_GIFTS_ROUTE_DEFINITION,
  ADMIN_SUPPORT_ROUTE_DEFINITION,
  ADMIN_MODERATOR_GOVERNANCE_ROUTE_DEFINITION,
]);
