import { CALLBACK_PHASE, CALLBACK_ROUTE } from '../../router/callbackContracts.js';
import {
  CURATOR_MANAGEMENT_ACTIONS,
  CURATOR_OPERATION_ACTIONS,
} from './actions.js';

export const CURATOR_OPERATIONS_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.CURATOR_OPERATIONS,
  phase: CALLBACK_PHASE.POST_USER,
  actions: CURATOR_OPERATION_ACTIONS,
});

export const CURATOR_MANAGEMENT_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.CURATOR_MANAGEMENT,
  phase: CALLBACK_PHASE.POST_USER,
  actions: CURATOR_MANAGEMENT_ACTIONS,
});

export const CURATOR_CALLBACK_ROUTE_DEFINITIONS = Object.freeze([
  CURATOR_OPERATIONS_ROUTE_DEFINITION,
  CURATOR_MANAGEMENT_ROUTE_DEFINITION,
]);
