import { CALLBACK_PHASE, CALLBACK_ROUTE } from '../../router/callbackContracts.js';
import {
  BARTER_CONVERSATION_ACTIONS,
  BARTER_DISCOVERY_ACTIONS,
  BARTER_OFFICIAL_ACTIONS,
  BARTER_OFFER_ACTIONS,
} from './actions.js';

export const BARTER_DISCOVERY_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.BARTER_DISCOVERY,
  phase: CALLBACK_PHASE.POST_USER,
  actions: BARTER_DISCOVERY_ACTIONS,
});

export const BARTER_OFFICIAL_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.BARTER_OFFICIAL,
  phase: CALLBACK_PHASE.POST_USER,
  actions: BARTER_OFFICIAL_ACTIONS,
});

export const BARTER_CONVERSATION_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.BARTER_CONVERSATIONS,
  phase: CALLBACK_PHASE.POST_USER,
  actions: BARTER_CONVERSATION_ACTIONS,
});

export const BARTER_OFFER_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.BARTER_OFFERS,
  phase: CALLBACK_PHASE.POST_USER,
  actions: BARTER_OFFER_ACTIONS,
});

export const BARTER_CALLBACK_ROUTE_DEFINITIONS = Object.freeze([
  BARTER_DISCOVERY_ROUTE_DEFINITION,
  BARTER_OFFICIAL_ROUTE_DEFINITION,
  BARTER_CONVERSATION_ROUTE_DEFINITION,
  BARTER_OFFER_ROUTE_DEFINITION,
]);
