export const BROADCAST_ACTION = Object.freeze({
  START: 'a:bc_start',
  START_ADVANCED: 'a:bc_start_adv',
  SIMPLE_TEXT: 'a:bc_simple_text',
  SIMPLE_MEDIA: 'a:bc_simple_media',
  SIMPLE_MEDIA_CLEAR: 'a:bc_simple_media_clear',
  SIMPLE_BUTTON: 'a:bc_simple_button',
  SIMPLE_BUTTON_PRESET: 'a:bc_simple_btn_preset',
  SIMPLE_BUTTON_CUSTOM: 'a:bc_simple_btn_custom',
  SIMPLE_BUTTON_CLEAR: 'a:bc_simple_btn_clear',
  SIMPLE_AUDIENCE: 'a:bc_simple_audience',
  PREVIEW: 'a:bc_preview',
  SEND_QUESTION: 'a:bc_send_q',
  SIMPLE_CLEAR: 'a:bc_simple_clear',
  AUDIENCE: 'a:bc_audience',
  BUTTONS: 'a:bc_buttons',
  TEMPLATE_GIVEAWAY: 'a:bc_tpl_gw',
  TEMPLATE_BRAND_PROFILE: 'a:bc_tpl_bp',
  TEMPLATE_OFFER: 'a:bc_tpl_offer',
  BUTTONS_DONE: 'a:bc_btn_done',
  CONFIRM: 'a:bc_confirm',
  CANCEL: 'a:bc_cancel',
  LIST: 'a:bc_list',
  VIEW: 'a:bc_view',
  BLOCKED: 'a:bc_blocked',
  PAUSE: 'a:bc_pause',
  RESUME: 'a:bc_resume',
  STOP: 'a:bc_stop',
  QSTASH_TOGGLE: 'a:admin_bc_qstash_toggle',
});

export const BROADCAST_COMPOSER_ACTIONS = Object.freeze([
  BROADCAST_ACTION.START,
  BROADCAST_ACTION.START_ADVANCED,
  BROADCAST_ACTION.SIMPLE_TEXT,
  BROADCAST_ACTION.SIMPLE_MEDIA,
  BROADCAST_ACTION.SIMPLE_MEDIA_CLEAR,
  BROADCAST_ACTION.SIMPLE_BUTTON,
  BROADCAST_ACTION.SIMPLE_BUTTON_PRESET,
  BROADCAST_ACTION.SIMPLE_BUTTON_CUSTOM,
  BROADCAST_ACTION.SIMPLE_BUTTON_CLEAR,
  BROADCAST_ACTION.PREVIEW,
  BROADCAST_ACTION.SEND_QUESTION,
  BROADCAST_ACTION.SIMPLE_CLEAR,
  BROADCAST_ACTION.BUTTONS,
  BROADCAST_ACTION.TEMPLATE_GIVEAWAY,
  BROADCAST_ACTION.TEMPLATE_BRAND_PROFILE,
  BROADCAST_ACTION.TEMPLATE_OFFER,
  BROADCAST_ACTION.BUTTONS_DONE,
]);

export const BROADCAST_AUDIENCE_ACTIONS = Object.freeze([
  BROADCAST_ACTION.SIMPLE_AUDIENCE,
  BROADCAST_ACTION.AUDIENCE,
]);

export const BROADCAST_DISPATCH_ACTIONS = Object.freeze([
  BROADCAST_ACTION.CONFIRM,
  BROADCAST_ACTION.CANCEL,
]);

export const BROADCAST_OPERATIONS_ACTIONS = Object.freeze([
  BROADCAST_ACTION.LIST,
  BROADCAST_ACTION.VIEW,
  BROADCAST_ACTION.BLOCKED,
  BROADCAST_ACTION.PAUSE,
  BROADCAST_ACTION.RESUME,
  BROADCAST_ACTION.STOP,
  BROADCAST_ACTION.QSTASH_TOGGLE,
]);

export const BROADCAST_CRITICAL_CALLBACK_ACTIONS = Object.freeze([
  ...BROADCAST_COMPOSER_ACTIONS,
  ...BROADCAST_AUDIENCE_ACTIONS,
  ...BROADCAST_DISPATCH_ACTIONS,
  ...BROADCAST_OPERATIONS_ACTIONS,
]);
