import { CALLBACK_PHASE, CALLBACK_ROUTE } from '../../router/callbackContracts.js';
import {
  BROADCAST_AUDIENCE_ACTIONS,
  BROADCAST_COMPOSER_ACTIONS,
  BROADCAST_DISPATCH_ACTIONS,
  BROADCAST_OPERATIONS_ACTIONS,
} from './actions.js';

export const BROADCAST_COMPOSER_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.BROADCAST_COMPOSER,
  phase: CALLBACK_PHASE.POST_USER,
  actions: BROADCAST_COMPOSER_ACTIONS,
});

export const BROADCAST_AUDIENCE_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.BROADCAST_AUDIENCE,
  phase: CALLBACK_PHASE.POST_USER,
  actions: BROADCAST_AUDIENCE_ACTIONS,
});

export const BROADCAST_DISPATCH_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.BROADCAST_DISPATCH,
  phase: CALLBACK_PHASE.POST_USER,
  actions: BROADCAST_DISPATCH_ACTIONS,
});

export const BROADCAST_OPERATIONS_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.BROADCAST_OPERATIONS,
  phase: CALLBACK_PHASE.POST_USER,
  actions: BROADCAST_OPERATIONS_ACTIONS,
});

export const BROADCAST_CALLBACK_ROUTE_DEFINITIONS = Object.freeze([
  BROADCAST_COMPOSER_ROUTE_DEFINITION,
  BROADCAST_AUDIENCE_ROUTE_DEFINITION,
  BROADCAST_DISPATCH_ROUTE_DEFINITION,
  BROADCAST_OPERATIONS_ROUTE_DEFINITION,
]);
