import { CALLBACK_PHASE, CALLBACK_ROUTE } from '../../router/callbackContracts.js';
import {
  ADMIN_AUTH_CHALLENGE_ACTIONS,
  ADMIN_AUTH_CONTROL_ACTIONS,
} from './actions.js';

export const ADMIN_AUTH_CHALLENGE_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.ADMIN_WEB_AUTH,
  phase: CALLBACK_PHASE.PRE_USER,
  actions: ADMIN_AUTH_CHALLENGE_ACTIONS,
});

export const ADMIN_AUTH_CONTROL_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.ADMIN_WEB_AUTH_CONTROL,
  phase: CALLBACK_PHASE.POST_USER,
  actions: ADMIN_AUTH_CONTROL_ACTIONS,
});

export const ADMIN_AUTH_CALLBACK_ROUTE_DEFINITIONS = Object.freeze([
  ADMIN_AUTH_CHALLENGE_ROUTE_DEFINITION,
  ADMIN_AUTH_CONTROL_ROUTE_DEFINITION,
]);
