export const ADMIN_SYSTEM_ACTION = Object.freeze({
  ADMIN: 'a:admin',
  ADMIN_HOME: 'a:admin_home',
  ADMIN_OPS: 'a:admin_ops',
  ADMIN_SYS: 'a:admin_sys',
  ADMIN_OPS_FLUSH: 'a:admin_ops_flush',
  ADMIN_OPS_PENDING_CLEAR: 'a:admin_ops_pending_clear',
  ADMIN_OPS_PENDING_CLEAR_DO: 'a:admin_ops_pending_clear_do',
  ADMIN_INVITES: 'a:admin_invites',
  ADMIN_INVITES_LIST: 'a:admin_invites_list',
  HS_HOME: 'a:hs_home',
  HS_HITS: 'a:hs_hits',
  HS_FIND: 'a:hs_find',
  HS_VIEW: 'a:hs_view',
  HS_UNSKIP: 'a:hs_unskip',
  HS_HITS_EXPORT: 'a:hs_hits_export',
  AUD: 'a:aud',
  AUD_SEARCH: 'a:aud_search',
  AUD_RESET: 'a:aud_reset',
  AUD_EXPORT: 'a:aud_export',
  ADMIN_METRICS: 'a:admin_metrics',
  ADMIN_QSTASH_STATUS: 'a:admin_qstash_status',
  ADMIN_QSTASH_PING: 'a:admin_qstash_ping',
  ADMIN_FOUNDER: 'a:admin_founder',
  ADMIN_FOUNDER_TOGGLE: 'a:admin_founder_toggle',
  ADMIN_FOUNDER_RESET: 'a:admin_founder_reset',
  ADMIN_FOUNDER_SET_DEADLINE: 'a:admin_founder_set_deadline',
  ADMIN_FOUNDER_SET_PRICES: 'a:admin_founder_set_prices',
  ADMIN_FOUNDER_SET_CREDITS: 'a:admin_founder_set_credits',
  ADMIN_FOUNDER_LINKS: 'a:admin_founder_links',
  ADMIN_FOUNDER_TEXTS: 'a:admin_founder_texts',
});

export const ADMIN_SYSTEM_NAVIGATION_ACTIONS = Object.freeze([
  ADMIN_SYSTEM_ACTION.ADMIN,
  ADMIN_SYSTEM_ACTION.ADMIN_HOME,
  ADMIN_SYSTEM_ACTION.ADMIN_OPS,
  ADMIN_SYSTEM_ACTION.ADMIN_SYS,
]);

export const ADMIN_SYSTEM_OPERATION_ACTIONS = Object.freeze([
  ADMIN_SYSTEM_ACTION.ADMIN_OPS_FLUSH,
  ADMIN_SYSTEM_ACTION.ADMIN_OPS_PENDING_CLEAR,
  ADMIN_SYSTEM_ACTION.ADMIN_OPS_PENDING_CLEAR_DO,
  ADMIN_SYSTEM_ACTION.ADMIN_INVITES,
  ADMIN_SYSTEM_ACTION.ADMIN_INVITES_LIST,
]);

export const ADMIN_DELIVERY_HARD_SKIP_ACTIONS = Object.freeze([
  ADMIN_SYSTEM_ACTION.HS_HOME,
  ADMIN_SYSTEM_ACTION.HS_HITS,
  ADMIN_SYSTEM_ACTION.HS_FIND,
  ADMIN_SYSTEM_ACTION.HS_VIEW,
  ADMIN_SYSTEM_ACTION.HS_UNSKIP,
  ADMIN_SYSTEM_ACTION.HS_HITS_EXPORT,
]);

export const ADMIN_AUDIT_METRIC_ACTIONS = Object.freeze([
  ADMIN_SYSTEM_ACTION.AUD,
  ADMIN_SYSTEM_ACTION.AUD_SEARCH,
  ADMIN_SYSTEM_ACTION.AUD_RESET,
  ADMIN_SYSTEM_ACTION.AUD_EXPORT,
  ADMIN_SYSTEM_ACTION.ADMIN_METRICS,
]);

export const ADMIN_QSTASH_ACTIONS = Object.freeze([
  ADMIN_SYSTEM_ACTION.ADMIN_QSTASH_STATUS,
  ADMIN_SYSTEM_ACTION.ADMIN_QSTASH_PING,
]);

export const ADMIN_FOUNDER_CONTROL_ACTIONS = Object.freeze([
  ADMIN_SYSTEM_ACTION.ADMIN_FOUNDER,
  ADMIN_SYSTEM_ACTION.ADMIN_FOUNDER_TOGGLE,
  ADMIN_SYSTEM_ACTION.ADMIN_FOUNDER_RESET,
  ADMIN_SYSTEM_ACTION.ADMIN_FOUNDER_SET_DEADLINE,
  ADMIN_SYSTEM_ACTION.ADMIN_FOUNDER_SET_PRICES,
  ADMIN_SYSTEM_ACTION.ADMIN_FOUNDER_SET_CREDITS,
  ADMIN_SYSTEM_ACTION.ADMIN_FOUNDER_LINKS,
  ADMIN_SYSTEM_ACTION.ADMIN_FOUNDER_TEXTS,
]);

export const ADMIN_SYSTEM_CALLBACK_ACTIONS = Object.freeze([
  ...ADMIN_SYSTEM_NAVIGATION_ACTIONS,
  ...ADMIN_SYSTEM_OPERATION_ACTIONS,
  ...ADMIN_DELIVERY_HARD_SKIP_ACTIONS,
  ...ADMIN_AUDIT_METRIC_ACTIONS,
  ...ADMIN_QSTASH_ACTIONS,
  ...ADMIN_FOUNDER_CONTROL_ACTIONS,
]);
