import { CALLBACK_PHASE, CALLBACK_ROUTE } from '../../router/callbackContracts.js';
import {
  ADMIN_AUDIT_METRIC_ACTIONS,
  ADMIN_DELIVERY_HARD_SKIP_ACTIONS,
  ADMIN_FOUNDER_CONTROL_ACTIONS,
  ADMIN_QSTASH_ACTIONS,
  ADMIN_SYSTEM_NAVIGATION_ACTIONS,
  ADMIN_SYSTEM_OPERATION_ACTIONS,
} from './actions.js';

export const ADMIN_SYSTEM_NAVIGATION_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.ADMIN_SYSTEM_NAVIGATION,
  phase: CALLBACK_PHASE.POST_USER,
  actions: ADMIN_SYSTEM_NAVIGATION_ACTIONS,
});
export const ADMIN_SYSTEM_OPERATION_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.ADMIN_SYSTEM_OPERATIONS,
  phase: CALLBACK_PHASE.POST_USER,
  actions: ADMIN_SYSTEM_OPERATION_ACTIONS,
});
export const ADMIN_DELIVERY_HARD_SKIP_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.ADMIN_DELIVERY_HARD_SKIP,
  phase: CALLBACK_PHASE.POST_USER,
  actions: ADMIN_DELIVERY_HARD_SKIP_ACTIONS,
});
export const ADMIN_AUDIT_METRIC_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.ADMIN_AUDIT_METRICS,
  phase: CALLBACK_PHASE.POST_USER,
  actions: ADMIN_AUDIT_METRIC_ACTIONS,
});
export const ADMIN_QSTASH_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.ADMIN_QSTASH_CONTROLS,
  phase: CALLBACK_PHASE.POST_USER,
  actions: ADMIN_QSTASH_ACTIONS,
});
export const ADMIN_FOUNDER_CONTROL_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.ADMIN_FOUNDER_CONTROLS,
  phase: CALLBACK_PHASE.POST_USER,
  actions: ADMIN_FOUNDER_CONTROL_ACTIONS,
});

export const ADMIN_SYSTEM_CALLBACK_ROUTE_DEFINITIONS = Object.freeze([
  ADMIN_SYSTEM_NAVIGATION_ROUTE_DEFINITION,
  ADMIN_SYSTEM_OPERATION_ROUTE_DEFINITION,
  ADMIN_DELIVERY_HARD_SKIP_ROUTE_DEFINITION,
  ADMIN_AUDIT_METRIC_ROUTE_DEFINITION,
  ADMIN_QSTASH_ROUTE_DEFINITION,
  ADMIN_FOUNDER_CONTROL_ROUTE_DEFINITION,
]);
