export const ADMIN_COMMUNICATION_ACTION = Object.freeze({
  ADMIN_COMMS: 'a:admin_comms',
  ADMIN_NOTICE: 'a:admin_notice',
  ADMIN_NOTICE_TOGGLE: 'a:admin_notice_toggle',
  ADMIN_NOTICE_SEV: 'a:admin_notice_sev',
  ADMIN_NOTICE_TARGET: 'a:admin_notice_target',
  ADMIN_NOTICE_CTA: 'a:admin_notice_cta',
  ADMIN_NOTICE_EXPIRE: 'a:admin_notice_expire',
  ADMIN_NOTICE_CLEAR: 'a:admin_notice_clear',
  ADMIN_NOTICE_PUBLISH: 'a:admin_notice_publish',
  ADMIN_NOTICE_TEXT: 'a:admin_notice_text',
  ADMIN_OUTBOX: 'a:admin_outbox',
  ADMIN_OUTBOX_V: 'a:admin_outbox_v',
  ADMIN_OUTBOX_NOTE: 'a:admin_outbox_note',
  ADMIN_OUTBOX_REPEAT: 'a:admin_outbox_repeat',
  ADMIN_OUTBOX_TO_TPL: 'a:admin_outbox_to_tpl',
  ADMIN_OUTBOX_CLEAR_Q: 'a:admin_outbox_clear_q',
  ADMIN_OUTBOX_CLEAR: 'a:admin_outbox_clear',
  ADM_PH: 'a:adm_ph',
  ADM_UMSG_TPL: 'a:adm_umsg_tpl',
  ADMIN_UMSG_TPLS: 'a:admin_umsg_tpls',
  ADMIN_UMSG_TPL_VIEW: 'a:admin_umsg_tpl_view',
  ADMIN_UMSG_TPL_ADD: 'a:admin_umsg_tpl_add',
  ADMIN_UMSG_TPL_EDIT: 'a:admin_umsg_tpl_edit',
  ADMIN_UMSG_TPL_DEL_Q: 'a:admin_umsg_tpl_del_q',
  ADMIN_UMSG_TPL_DEL: 'a:admin_umsg_tpl_del',
  ADMIN_UMSG_TPL_RESET_Q: 'a:admin_umsg_tpl_reset_q',
  ADMIN_UMSG_TPL_RESET: 'a:admin_umsg_tpl_reset',
});

export const ADMIN_COMMUNICATION_HOME_ACTIONS = Object.freeze([
  ADMIN_COMMUNICATION_ACTION.ADMIN_COMMS,
]);

export const ADMIN_NOTICE_ACTIONS = Object.freeze([
  ADMIN_COMMUNICATION_ACTION.ADMIN_NOTICE,
  ADMIN_COMMUNICATION_ACTION.ADMIN_NOTICE_TOGGLE,
  ADMIN_COMMUNICATION_ACTION.ADMIN_NOTICE_SEV,
  ADMIN_COMMUNICATION_ACTION.ADMIN_NOTICE_TARGET,
  ADMIN_COMMUNICATION_ACTION.ADMIN_NOTICE_CTA,
  ADMIN_COMMUNICATION_ACTION.ADMIN_NOTICE_EXPIRE,
  ADMIN_COMMUNICATION_ACTION.ADMIN_NOTICE_CLEAR,
  ADMIN_COMMUNICATION_ACTION.ADMIN_NOTICE_PUBLISH,
  ADMIN_COMMUNICATION_ACTION.ADMIN_NOTICE_TEXT,
]);

export const ADMIN_OUTBOX_ACTIONS = Object.freeze([
  ADMIN_COMMUNICATION_ACTION.ADMIN_OUTBOX,
  ADMIN_COMMUNICATION_ACTION.ADMIN_OUTBOX_V,
  ADMIN_COMMUNICATION_ACTION.ADMIN_OUTBOX_NOTE,
  ADMIN_COMMUNICATION_ACTION.ADMIN_OUTBOX_REPEAT,
  ADMIN_COMMUNICATION_ACTION.ADMIN_OUTBOX_TO_TPL,
  ADMIN_COMMUNICATION_ACTION.ADMIN_OUTBOX_CLEAR_Q,
  ADMIN_COMMUNICATION_ACTION.ADMIN_OUTBOX_CLEAR,
]);

export const ADMIN_MESSAGE_TEMPLATE_ACTIONS = Object.freeze([
  ADMIN_COMMUNICATION_ACTION.ADM_PH,
  ADMIN_COMMUNICATION_ACTION.ADM_UMSG_TPL,
  ADMIN_COMMUNICATION_ACTION.ADMIN_UMSG_TPLS,
  ADMIN_COMMUNICATION_ACTION.ADMIN_UMSG_TPL_VIEW,
  ADMIN_COMMUNICATION_ACTION.ADMIN_UMSG_TPL_ADD,
  ADMIN_COMMUNICATION_ACTION.ADMIN_UMSG_TPL_EDIT,
  ADMIN_COMMUNICATION_ACTION.ADMIN_UMSG_TPL_DEL_Q,
  ADMIN_COMMUNICATION_ACTION.ADMIN_UMSG_TPL_DEL,
  ADMIN_COMMUNICATION_ACTION.ADMIN_UMSG_TPL_RESET_Q,
  ADMIN_COMMUNICATION_ACTION.ADMIN_UMSG_TPL_RESET,
]);

export const ADMIN_COMMUNICATION_CALLBACK_ACTIONS = Object.freeze([
  ...ADMIN_COMMUNICATION_HOME_ACTIONS,
  ...ADMIN_NOTICE_ACTIONS,
  ...ADMIN_OUTBOX_ACTIONS,
  ...ADMIN_MESSAGE_TEMPLATE_ACTIONS,
]);
