import { CALLBACK_PHASE, CALLBACK_ROUTE } from '../../router/callbackContracts.js';
import {
  ADMIN_COMMUNICATION_HOME_ACTIONS,
  ADMIN_MESSAGE_TEMPLATE_ACTIONS,
  ADMIN_NOTICE_ACTIONS,
  ADMIN_OUTBOX_ACTIONS,
} from './actions.js';

export const ADMIN_COMMUNICATION_HOME_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.ADMIN_COMMUNICATIONS,
  phase: CALLBACK_PHASE.POST_USER,
  actions: ADMIN_COMMUNICATION_HOME_ACTIONS,
});

export const ADMIN_NOTICE_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.ADMIN_NOTICE_MANAGEMENT,
  phase: CALLBACK_PHASE.POST_USER,
  actions: ADMIN_NOTICE_ACTIONS,
});

export const ADMIN_OUTBOX_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.ADMIN_OUTBOX,
  phase: CALLBACK_PHASE.POST_USER,
  actions: ADMIN_OUTBOX_ACTIONS,
});

export const ADMIN_MESSAGE_TEMPLATE_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.ADMIN_MESSAGE_TEMPLATES,
  phase: CALLBACK_PHASE.POST_USER,
  actions: ADMIN_MESSAGE_TEMPLATE_ACTIONS,
});

export const ADMIN_COMMUNICATION_CALLBACK_ROUTE_DEFINITIONS = Object.freeze([
  ADMIN_COMMUNICATION_HOME_ROUTE_DEFINITION,
  ADMIN_NOTICE_ROUTE_DEFINITION,
  ADMIN_OUTBOX_ROUTE_DEFINITION,
  ADMIN_MESSAGE_TEMPLATE_ROUTE_DEFINITION,
]);
