export const BRAND_ACTION = Object.freeze({
  BRANDS_HOME: 'a:brands_home',
  BRANDS_FILTERS: 'a:brands_filters',
  BD_FPICK: 'a:bd_fpick',
  BD_FRESET: 'a:bd_freset',
  BD_FSET: 'a:bd_fset',
  BD_MCLEAR: 'a:bd_mclear',
  BD_MDONE: 'a:bd_mdone',
  BD_MPICK: 'a:bd_mpick',
  BD_MT: 'a:bd_mt',
  BRAND_DIR_OPEN: 'a:brand_dir_open',
  BRAND_PROFILE: 'a:brand_profile',
  BRAND_PROFILE_EDIT: 'a:brand_profile_edit',
  BRAND_PROFILE_MORE: 'a:brand_profile_more',
  BRAND_CONTINUE: 'a:brand_continue',
  BRAND_PROF_MORE: 'a:brand_prof_more',
  BRAND_PROF_SET: 'a:brand_prof_set',
  BRAND_NICHE_PICK: 'a:brand_niche_pick',
  BRAND_NICHE_SET: 'a:brand_niche_set',
  BRAND_NICHE_CLEAR: 'a:brand_niche_clear',
  BRAND_TY_T: 'a:brand_ty_t',
  BRAND_TY_CLEAR: 'a:brand_ty_clear',
  BRAND_TY_DONE: 'a:brand_ty_done',
  BRAND_BB_PICK: 'a:brand_bb_pick',
  BRAND_BB_SET: 'a:brand_bb_set',
  BRAND_BB_CLEAR: 'a:brand_bb_clear',
  BRAND_BB_DONE: 'a:brand_bb_done',
  BRAND_GT_PICK: 'a:brand_gt_pick',
  BRAND_GT_T: 'a:brand_gt_t',
  BRAND_GT_CLEAR: 'a:brand_gt_clear',
  BRAND_GT_DONE: 'a:brand_gt_done',
  BRAND_RT_PICK: 'a:brand_rt_pick',
  BRAND_RT_T: 'a:brand_rt_t',
  BRAND_RT_CLEAR: 'a:brand_rt_clear',
  BRAND_RT_DONE: 'a:brand_rt_done',
  BRAND_PROF_RESET: 'a:brand_prof_reset',
  BRAND_PROF_RESET_OK: 'a:brand_prof_reset_ok',
  BRAND_PASS: 'a:brand_pass',
  BRAND_PLAN: 'a:brand_plan',
});

export const BRAND_DIRECTORY_ACTIONS = Object.freeze([
  BRAND_ACTION.BRANDS_HOME,
  BRAND_ACTION.BRANDS_FILTERS,
  BRAND_ACTION.BD_FPICK,
  BRAND_ACTION.BD_FRESET,
  BRAND_ACTION.BD_FSET,
  BRAND_ACTION.BD_MCLEAR,
  BRAND_ACTION.BD_MDONE,
  BRAND_ACTION.BD_MPICK,
  BRAND_ACTION.BD_MT,
  BRAND_ACTION.BRAND_DIR_OPEN,
]);

export const BRAND_PROFILE_ACTIONS = Object.freeze([
  BRAND_ACTION.BRAND_PROFILE,
  BRAND_ACTION.BRAND_PROFILE_EDIT,
  BRAND_ACTION.BRAND_PROFILE_MORE,
  BRAND_ACTION.BRAND_CONTINUE,
  BRAND_ACTION.BRAND_PROF_MORE,
  BRAND_ACTION.BRAND_PROF_SET,
  BRAND_ACTION.BRAND_NICHE_PICK,
  BRAND_ACTION.BRAND_NICHE_SET,
  BRAND_ACTION.BRAND_NICHE_CLEAR,
  BRAND_ACTION.BRAND_TY_T,
  BRAND_ACTION.BRAND_TY_CLEAR,
  BRAND_ACTION.BRAND_TY_DONE,
  BRAND_ACTION.BRAND_BB_PICK,
  BRAND_ACTION.BRAND_BB_SET,
  BRAND_ACTION.BRAND_BB_CLEAR,
  BRAND_ACTION.BRAND_BB_DONE,
  BRAND_ACTION.BRAND_GT_PICK,
  BRAND_ACTION.BRAND_GT_T,
  BRAND_ACTION.BRAND_GT_CLEAR,
  BRAND_ACTION.BRAND_GT_DONE,
  BRAND_ACTION.BRAND_RT_PICK,
  BRAND_ACTION.BRAND_RT_T,
  BRAND_ACTION.BRAND_RT_CLEAR,
  BRAND_ACTION.BRAND_RT_DONE,
  BRAND_ACTION.BRAND_PROF_RESET,
  BRAND_ACTION.BRAND_PROF_RESET_OK,
  BRAND_ACTION.BRAND_PASS,
  BRAND_ACTION.BRAND_PLAN,
]);

export const BRAND_CALLBACK_ACTIONS = Object.freeze([
  ...BRAND_DIRECTORY_ACTIONS,
  ...BRAND_PROFILE_ACTIONS,
]);
