import { CALLBACK_PHASE, CALLBACK_ROUTE } from '../../router/callbackContracts.js';
import {
  BRAND_DIRECTORY_ACTIONS,
  BRAND_MANAGER_MODE_ACTIONS,
  BRAND_PROFILE_ACTIONS,
  BRAND_TEAM_MEMBERSHIP_ACTIONS,
} from './actions.js';

export const BRAND_DIRECTORY_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.BRAND_DIRECTORY,
  phase: CALLBACK_PHASE.POST_USER,
  actions: BRAND_DIRECTORY_ACTIONS,
});

export const BRAND_PROFILE_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.BRAND_PROFILE,
  phase: CALLBACK_PHASE.POST_USER,
  actions: BRAND_PROFILE_ACTIONS,
});


export const BRAND_MANAGER_MODE_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.BRAND_MANAGER_MODE,
  phase: CALLBACK_PHASE.POST_USER,
  actions: BRAND_MANAGER_MODE_ACTIONS,
});

export const BRAND_TEAM_MEMBERSHIP_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.BRAND_TEAM_MEMBERSHIP,
  phase: CALLBACK_PHASE.POST_USER,
  actions: BRAND_TEAM_MEMBERSHIP_ACTIONS,
});

export const BRAND_CALLBACK_ROUTE_DEFINITIONS = Object.freeze([
  BRAND_DIRECTORY_ROUTE_DEFINITION,
  BRAND_PROFILE_ROUTE_DEFINITION,
  BRAND_MANAGER_MODE_ROUTE_DEFINITION,
  BRAND_TEAM_MEMBERSHIP_ROUTE_DEFINITION,
]);
