export const PAYMENT_ACTION = Object.freeze({
  FOUNDER_BUY: 'a:founder_buy',
  WORKSPACE_PRO_BUY: 'a:ws_pro_buy',
  BRAND_CREDITS_BUY: 'a:brand_buy',
  BRAND_PLAN_BUY: 'a:brand_plan_buy',
  MATCHING_BUY: 'a:match_buy',
  FEATURED_BUY: 'a:feat_buy',

  ADMIN_ACCEPT_TOGGLE: 'a:admin_pay_accept_toggle',
  ADMIN_AUTO_APPLY_TOGGLE: 'a:admin_pay_auto_toggle',
  ADMIN_FALLBACK_HOME: 'a:admin_pay_fb',
  ADMIN_FALLBACK_ENABLE: 'a:admin_pay_fb_set',
  ADMIN_FALLBACK_DISABLE: 'a:admin_pay_fb_off',
  ADMIN_MATCHFEAT_AUTO_TOGGLE: 'a:admin_matchfeat_auto_toggle',
  ADMIN_LEDGER: 'a:admin_payments',
  ADMIN_LEDGER_VIEW: 'a:admin_pay_view',
  ADMIN_LEDGER_APPLY: 'a:admin_pay_apply',
  ADMIN_LEDGER_AUTOHEAL: 'a:admin_pay_autoheal',
});

export const PAYMENT_PURCHASE_ACTIONS = Object.freeze([
  PAYMENT_ACTION.FOUNDER_BUY,
  PAYMENT_ACTION.WORKSPACE_PRO_BUY,
  PAYMENT_ACTION.BRAND_CREDITS_BUY,
  PAYMENT_ACTION.BRAND_PLAN_BUY,
  PAYMENT_ACTION.MATCHING_BUY,
  PAYMENT_ACTION.FEATURED_BUY,
]);

export const PAYMENT_ADMIN_ACTIONS = Object.freeze([
  PAYMENT_ACTION.ADMIN_ACCEPT_TOGGLE,
  PAYMENT_ACTION.ADMIN_AUTO_APPLY_TOGGLE,
  PAYMENT_ACTION.ADMIN_FALLBACK_HOME,
  PAYMENT_ACTION.ADMIN_FALLBACK_ENABLE,
  PAYMENT_ACTION.ADMIN_FALLBACK_DISABLE,
  PAYMENT_ACTION.ADMIN_MATCHFEAT_AUTO_TOGGLE,
  PAYMENT_ACTION.ADMIN_LEDGER,
  PAYMENT_ACTION.ADMIN_LEDGER_VIEW,
  PAYMENT_ACTION.ADMIN_LEDGER_APPLY,
  PAYMENT_ACTION.ADMIN_LEDGER_AUTOHEAL,
]);

export const PAYMENT_CALLBACK_ACTIONS = Object.freeze([
  ...PAYMENT_PURCHASE_ACTIONS,
  ...PAYMENT_ADMIN_ACTIONS,
]);
