import { CALLBACK_PHASE, CALLBACK_ROUTE } from '../../router/callbackContracts.js';
import {
  PAYMENT_ADMIN_ACTIONS,
  PAYMENT_PURCHASE_ACTIONS,
} from './actions.js';

export const PAYMENT_PURCHASE_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.PAYMENT_PURCHASE,
  phase: CALLBACK_PHASE.POST_USER,
  actions: PAYMENT_PURCHASE_ACTIONS,
});

export const PAYMENT_ADMIN_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.PAYMENT_ADMIN,
  phase: CALLBACK_PHASE.POST_USER,
  actions: PAYMENT_ADMIN_ACTIONS,
});

export const PAYMENT_CALLBACK_ROUTE_DEFINITIONS = Object.freeze([
  PAYMENT_PURCHASE_ROUTE_DEFINITION,
  PAYMENT_ADMIN_ROUTE_DEFINITION,
]);
