import { CALLBACK_PHASE, CALLBACK_ROUTE } from '../../router/callbackContracts.js';
import {
  LEAD_ACQUISITION_ACTIONS,
  LEAD_AUDIT_ACTIONS,
  LEAD_WORKFLOW_ACTIONS,
} from './actions.js';

export const LEAD_ACQUISITION_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.LEAD_ACQUISITION,
  phase: CALLBACK_PHASE.POST_USER,
  actions: LEAD_ACQUISITION_ACTIONS,
});

export const LEAD_WORKFLOW_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.LEAD_WORKFLOW,
  phase: CALLBACK_PHASE.POST_USER,
  actions: LEAD_WORKFLOW_ACTIONS,
});

export const LEAD_AUDIT_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.LEAD_AUDIT,
  phase: CALLBACK_PHASE.POST_USER,
  actions: LEAD_AUDIT_ACTIONS,
});

export const LEAD_CALLBACK_ROUTE_DEFINITIONS = Object.freeze([
  LEAD_ACQUISITION_ROUTE_DEFINITION,
  LEAD_WORKFLOW_ROUTE_DEFINITION,
  LEAD_AUDIT_ROUTE_DEFINITION,
]);
