import { CALLBACK_PHASE, CALLBACK_ROUTE } from '../../router/callbackContracts.js';
import { WORKSPACE_CONTROL_ACTIONS, WORKSPACE_FOLDER_ACTIONS } from './actions.js';

export const WORKSPACE_CONTROL_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.WORKSPACE_CONTROL,
  phase: CALLBACK_PHASE.POST_USER,
  actions: WORKSPACE_CONTROL_ACTIONS,
});

export const WORKSPACE_FOLDER_ROUTE_DEFINITION = Object.freeze({
  id: CALLBACK_ROUTE.WORKSPACE_FOLDERS,
  phase: CALLBACK_PHASE.POST_USER,
  actions: WORKSPACE_FOLDER_ACTIONS,
});

export const WORKSPACE_CALLBACK_ROUTE_DEFINITIONS = Object.freeze([
  WORKSPACE_CONTROL_ROUTE_DEFINITION,
  WORKSPACE_FOLDER_ROUTE_DEFINITION,
]);
